version: '3'

includes:
  pilot-task:
    taskfile: ./apps/aero-stream-pilot
    dir: ./apps/aero-stream-pilot
  tower-task:
    taskfile: ./apps/aero-stream-tower
    dir: ./apps/aero-stream-tower
  pilot-example:
    taskfile: ./apps/aero-stream-pilot-example
    dir: ./apps/aero-stream-pilot-example

tasks:
  default:
    desc: 'Show available tasks.'
    cmds:
      - task --list-all

  pilot:pack:
    cmds:
      - task: pilot-task:pack

  pilot:dev:
    cmds:
      - task: pilot-example:dev

  tower:dev:
    cmds:
      - task: tower-task:dev
