version: '3'

includes:
  pilot-task:
    taskfile: ../aero-stream-pilot
    dir: ../aero-stream-pilot

tasks:
  install:
    desc: 'Install dependencies.'
    cmds:
      - yarn install

  sync-pilot:
    desc: 'Build, clean cache and sync local aero-stream-pilot package'
    silent: false
    cmds:
      - task: pilot-task:pack
      - task: install

  build:
    desc: 'Build the worker for production.'
    deps:
      - sync-pilot
    cmds:
      - yarn build

  start:
    desc: 'Run the built worker locally.'
    deps:
      - build
    cmds:
      - yarn start

  dev:
    desc: 'Run the worker in development mode with hot-reloading.'
    deps:
      - sync-pilot
    cmds:
      - yarn dev

  deploy:
    desc: 'Deploy the worker to Cloudflare.'
    cmds:
      - echo "Deploy para Next.js no configurado. Utilizar Vercel o similar."

  test:
    desc: 'Run tests for the worker.'
    cmds:
      - echo "Not implemented"
    silent: true
